# Generated by Django 3.2.7 on 2021-10-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eloop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventlooptransaction",
            name="status",
            field=models.CharField(default="pending", max_length=255),
        ),
    ]
