# Generated by Django 3.2.7 on 2021-10-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankdetail",
            name="user",
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
