# Generated by Django 3.2.7 on 2021-10-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0002_alter_bankdetail_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upidetail",
            name="user",
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
