# Generated by Django 3.2.7 on 2021-10-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0003_alter_upidetail_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankdetail",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="upidetail",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
