# Generated by Django 3.2.7 on 2021-09-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="authenticated",
            field=models.BooleanField(default=False),
        ),
    ]
