# Generated by Django 3.2.7 on 2021-09-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_authenticated"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="finaltoken",
            field=models.CharField(default="no-token", max_length=255),
        ),
    ]
