# Generated by Django 3.2.7 on 2021-09-25 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_finaltoken"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="finaltoken",
            new_name="finaltok",
        ),
    ]
