# Generated by Django 3.2.7 on 2021-09-25 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_finaltoken_user_finaltok"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="finaltok",
        ),
    ]
