# Generated by Django 3.2.7 on 2021-09-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_user_finaltok"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="finaltok",
            field=models.CharField(default="no-token", max_length=255),
        ),
    ]
