# Generated by Django 3.2.7 on 2021-10-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_finaltok"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(default="donor", max_length=25),
            preserve_default=False,
        ),
    ]
