# Generated by Django 3.2.7 on 2021-10-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_auto_20211002_1653"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_id",
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(default="null", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="UserID",
        ),
    ]
