# Generated by Django 3.2.7 on 2021-10-02 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_auto_20211002_1655"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
    ]
