# Generated by Django 3.2.7 on 2021-10-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_auto_20211002_1710"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
