# Generated by Django 3.2.7 on 2021-10-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="creation_transaction_completed",
            field=models.BooleanField(default=False),
        ),
    ]
