# Generated by Django 3.2.7 on 2021-10-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraiser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundraisermilestones",
            name="milestone_desc",
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name="fundraisermilestones",
            name="milestone_id",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="fundraisermilestones",
            name="milestone_title",
            field=models.CharField(max_length=100),
        ),
    ]
