# Generated by Django 3.2.7 on 2021-10-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creator", models.EmailField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("img", models.ImageField(upload_to="imgs/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
