# Generated by Django 3.2.7 on 2021-10-03 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="creator",
            new_name="sent_to",
        ),
    ]
