# Generated by Django 3.2.7 on 2021-10-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_rename_creator_notification_sent_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="img",
            field=models.ImageField(upload_to="imgs/notifications/"),
        ),
    ]
