# Generated by Django 3.2.7 on 2021-10-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_alter_notification_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="img",
            field=models.ImageField(upload_to="imgs/notifications/"),
        ),
    ]
